import { Project } from "@/types";

export const sampleProjects: Project[] = [
    {
        id: "1",
        title: "Onboarding Process",
        status: "In progress",
        pic: {
            name: "Jenny Lim",
            avatarUrl: "https://i.pravatar.cc/150?u=jenny",
        },
        department: "Human Resource",
        role: "Talent Officer",
        completedTasks: 5,
        totalTasks: 21,
        deadline: "May 24, 2025",
        progress: 42,
        iconColor: "text-orange-500 bg-orange-100",
    },
    {
        id: "2",
        title: "Cybersecurity Policy Upda...",
        status: "Completed",
        pic: {
            name: "Michael Ardi",
            avatarUrl: "https://i.pravatar.cc/150?u=michael",
        },
        department: "Engineer",
        role: "IT Security Officer",
        completedTasks: 14,
        totalTasks: 14,
        deadline: "May 10, 2025",
        progress: 100,
        iconColor: "text-teal-500 bg-teal-100",
    },
    {
        id: "3",
        title: "Talent Development Program",
        status: "Pending",
        pic: {
            name: "Lisa Kim",
            avatarUrl: "https://i.pravatar.cc/150?u=lisa",
        },
        department: "Human Resource",
        role: "Talent Officer",
        completedTasks: 1,
        totalTasks: 12,
        deadline: "June 25, 2025",
        progress: 10,
        iconColor: "text-purple-500 bg-purple-100",
    },
    {
        id: "4",
        title: "Internship 2025",
        status: "Completed",
        pic: {
            name: "Peter Gabrielle",
            avatarUrl: "https://i.pravatar.cc/150?u=peter",
        },
        department: "Human Resource",
        role: "HR Lead",
        completedTasks: 3,
        totalTasks: 3,
        deadline: "May 30, 2025",
        progress: 100,
        iconColor: "text-cyan-500 bg-cyan-100",
    },
    {
        id: "5",
        title: "Network Infrastructure Up...",
        status: "In progress",
        pic: {
            name: "Daniel Chong",
            avatarUrl: "https://i.pravatar.cc/150?u=daniel",
        },
        department: "Engineer",
        role: "IT Lead",
        completedTasks: 9,
        totalTasks: 12,
        deadline: "June 10, 2025",
        progress: 75,
        iconColor: "text-amber-500 bg-amber-100",
    },
    {
        id: "6",
        title: "Website SEO Optimization",
        status: "Completed",
        pic: {
            name: "Thomas Yeo",
            avatarUrl: "https://i.pravatar.cc/150?u=thomas",
        },
        department: "Marketing",
        role: "SEO Specialist",
        completedTasks: 15,
        totalTasks: 15,
        deadline: "May 10, 2025",
        progress: 100,
        iconColor: "text-emerald-500 bg-emerald-100",
    },
];
